import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/layout/header/header'
import { Hero } from '@/components/ui/hero/hero'
import { BestSeller } from '@/components/ui/best-seller/best-seller'
import { BestServices } from '@/components/ui/best-services/best-services'
import { FeaturedPosts } from '@/components/ui/featured-posts/featured-posts'
import { AboutUs } from '@/components/ui/about-us/about-us'
import { Problems } from '@/components/ui/problems/problems'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Hero />
        <BestSeller />
        <BestServices />
        <FeaturedPosts />
        <AboutUs />
        <Problems />
      </>
  </>
  )
}
